load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "hello-triangle",
    srcs = ["hello-triangle.cpp"],
    deps = [
        "//third_party/libglfw",
        "//third_party/glad",
    ]
)